<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\EditableWord;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class SetEmailTemplateController extends Controller
{
    private $model;
    private $language_id;
    private static $error_flg = FALSE;
    private $word_id_array = [
        "DEFAULT_FROM",
        "FILE_SHARE_PROJECT_UPLOAD_MAIL_FROM",
        "FILE_SHARE_PROJECT_UPLOAD_MAIL_TITLE",
        "FILE_SHARE_PROJECT_UPLOAD_MAIL_BODY",
        "FILE_SHARE_PROJECT_DOWNLOAD_MAIL_FROM",
        "FILE_SHARE_PROJECT_DOWNLOAD_MAIL_TITLE",
        "FILE_SHARE_PROJECT_DOWNLOAD_MAIL_BODY",
        "FILE_SHARE_PROJECT_APPROVAL_MAIL_FROM",
        "FILE_SHARE_PROJECT_APPROVAL_MAIL_TITLE",
        "FILE_SHARE_PROJECT_APPROVAL_MAIL_BODY",
        "FILE_SHARE_PROJECT_APPROVAL_COMPLETION_MAIL_FROM",
        "FILE_SHARE_PROJECT_APPROVAL_COMPLETION_MAIL_TITLE",
        "FILE_SHARE_PROJECT_APPROVAL_COMPLETION_MAIL_BODY",
        "FILE_SHARE_PROJECT_REJECT_COMPLETION_MAIL_FROM",
        "FILE_SHARE_PROJECT_REJECT_COMPLETION_MAIL_TITLE",
        "FILE_SHARE_PROJECT_REJECT_COMPLETION_MAIL_BODY",
        "FILE_TRANSFER_MAIL_FROM",
        "FILE_TRANSFER_MAIL_TITLE",
        "FILE_TRANSFER_MAIL_BODY",
        "FILE_TRANSFER_PASSWORD_MAIL_TITLE",
        "FILE_TRANSFER_PASSWORD_MAIL_BODY",
        "FILE_TRANSFER_APPROVAL_MAIL_FROM",
        "FILE_TRANSFER_APPROVAL_MAIL_TITLE",
        "FILE_TRANSFER_APPROVAL_MAIL_BODY",
        "FILE_TRANSFER_APPROVAL_COMPLETION_MAIL_FROM",
        "FILE_TRANSFER_APPROVAL_COMPLETION_MAIL_TITLE",
        "FILE_TRANSFER_APPROVAL_COMPLETION_MAIL_BODY",
        "FILE_TRANSFER_REJECT_COMPLETION_MAIL_FROM",
        "FILE_TRANSFER_REJECT_COMPLETION_MAIL_TITLE",
        "FILE_TRANSFER_REJECT_COMPLETION_MAIL_BODY",
        "FILE_TRANSFER_DOWNLOAD_MAIL_FROM",
        "FILE_TRANSFER_DOWNLOAD_MAIL_TITLE",
        "FILE_TRANSFER_DOWNLOAD_MAIL_BODY",
        "FILE_TRANSFER_REPLY_MAIL_FROM",
        "FILE_TRANSFER_REPLY_MAIL_TITLE",
        "FILE_TRANSFER_REPLY_MAIL_BODY",
        "USER_TRANSFER_MAIL_FROM",
        "USER_TRANSFER_MAIL_TITLE",
        "USER_TRANSFER_MAIL_BODY",
        "USER_TRANSFER_APPROVAL_MAIL_FROM",
        "USER_TRANSFER_APPROVAL_MAIL_TITLE",
        "USER_TRANSFER_APPROVAL_MAIL_BODY",
        "USER_TRANSFER_APPROVAL_COMPLETION_MAIL_FROM",
        "USER_TRANSFER_APPROVAL_COMPLETION_MAIL_TITLE",
        "USER_TRANSFER_APPROVAL_COMPLETION_MAIL_BODY",
        "USER_TRANSFER_REJECT_COMPLETION_MAIL_FROM",
        "USER_TRANSFER_REJECT_COMPLETION_MAIL_TITLE",
        "USER_TRANSFER_REJECT_COMPLETION_MAIL_BODY",
        "USER_TRANSFER_DOWNLOAD_MAIL_FROM",
        "USER_TRANSFER_DOWNLOAD_MAIL_TITLE",
        "USER_TRANSFER_DOWNLOAD_MAIL_BODY",
        "USER_TRANSFER_REPLY_MAIL_FROM",
        "USER_TRANSFER_REPLY_MAIL_TITLE",
        "USER_TRANSFER_REPLY_MAIL_BODY",
        "USE_CAPACITY_WARNING_MAIL_FROM",
        "USE_CAPACITY_WARNING_MAIL_TITLE",
        "USE_CAPACITY_WARNING_MAIL_BODY",
        "PASSWORD_EXPIRATION_NOTIFICATION_MAIL_FROM",
        "PASSWORD_EXPIRATION_NOTIFICATION_MAIL_TITLE",
        "PASSWORD_EXPIRATION_NOTIFICATION_MAIL_BODY",
        "TERMINAL_LIMIT_NOTIFICATION_MAIL_FROM",
        "TERMINAL_LIMIT_NOTIFICATION_MAIL_TITLE",
        "TERMINAL_LIMIT_NOTIFICATION_MAIL_BODY",
        "FIRST_TIME_PASSWORD_MAIL_FROM",
        "FIRST_TIME_PASSWORD_MAIL_TITLE",
        "FIRST_TIME_PASSWORD_MAIL_BODY",
        "INVITATION_REISSUE_FROM",
        "INVITATION_REISSUE_TITLE",
        "INVITATION_REISSUE_BODY",
        "PASSWORD_REISSUE_MAIL_FROM",
        "PASSWORD_REISSUE_MAIL_TITLE",
        "PASSWORD_REISSUE_MAIL_BODY",
        "PASSWORD_REISSUE_NOTIFICATION_MAIL_TITLE",
        "PASSWORD_REISSUE_NOTIFICATION_MAIL_BODY",
        "PASSWORD_REISSUE_LDAP_ERROR_MAIL_FROM",
        "PASSWORD_REISSUE_LDAP_ERROR_MAIL_TITLE",
        "PASSWORD_REISSUE_LDAP_ERROR_MAIL_BODY",
        "PASSWORD_REISSUE_AUTH_ERROR_MAIL_FROM",
        "PASSWORD_REISSUE_AUTH_ERROR_MAIL_TITLE",
        "PASSWORD_REISSUE_AUTH_ERROR_MAIL_BODY",
        "FILE_SHARE_PROJECT_PDF_PASSWORD_MAIL_FROM",
        "FILE_SHARE_PROJECT_PDF_PASSWORD_MAIL_TITLE",
        "FILE_SHARE_PROJECT_PDF_PASSWORD_MAIL_BODY",
        "FILE_TRANSFER_PDF_PASSWORD_MAIL_FROM",
        "FILE_TRANSFER_PDF_PASSWORD_MAIL_TITLE",
        "FILE_TRANSFER_PDF_PASSWORD_MAIL_BODY",
        "FILE_SHARE_PROJECT_VIRUS_DETECTION_MAIL_TO",
        "FILE_SHARE_PROJECT_VIRUS_DETECTION_MAIL_FROM",
        "FILE_SHARE_PROJECT_VIRUS_DETECTION_MAIL_TITLE",
        "FILE_SHARE_PROJECT_VIRUS_DETECTION_MAIL_BODY",
        //ADD - 2017/10/31 - Fujinet - SF6.5.0_SF13-15-01 - START
        "FILE_TRANSFER_NO_CONVERSION_APPROVAL_MAIL_FROM",
        "FILE_TRANSFER_NO_CONVERSION_APPROVAL_MAIL_TITLE",
        "FILE_TRANSFER_NO_CONVERSION_APPROVAL_MAIL_BODY",
        "FILE_TRANSFER_NO_CONVERSION_APPROVAL_COMPLETION_MAIL_FROM",
        "FILE_TRANSFER_NO_CONVERSION_APPROVAL_COMPLETION_MAIL_TITLE",
        "FILE_TRANSFER_NO_CONVERSION_APPROVAL_COMPLETION_MAIL_BODY",
        "FILE_TRANSFER_NO_CONVERSION_REJECT_COMPLETION_MAIL_FROM",
        "FILE_TRANSFER_NO_CONVERSION_REJECT_COMPLETION_MAIL_TITLE",
        "FILE_TRANSFER_NO_CONVERSION_REJECT_COMPLETION_MAIL_BODY",
        //ADD - 2017/10/31 - Fujinet - SF6.5.0_SF13-15-01 - END
        //ADD - 2018/04/06 - Fujinet - SF6.7.0_SF13-15-01 - START
        "FILE_TRANSFER_MAIL_TITLE_WITH_FILE_NO_REPLY",
        "FILE_TRANSFER_MAIL_BODY_WITH_FILE_NO_REPLY",
        "FILE_TRANSFER_MAIL_TITLE_NO_FILE_WITH_REPLY",
        "FILE_TRANSFER_MAIL_BODY_NO_FILE_WITH_REPLY",
        "FILE_TRANSFER_PASSWORD_MAIL_TITLE_WITH_FILE_NO_REPLY",
        "FILE_TRANSFER_PASSWORD_MAIL_BODY_WITH_FILE_NO_REPLY",
        "FILE_TRANSFER_PASSWORD_MAIL_TITLE_NO_FILE_WITH_REPLY",
        "FILE_TRANSFER_PASSWORD_MAIL_BODY_NO_FILE_WITH_REPLY",
        "USER_TRANSFER_MAIL_TITLE_WITH_FILE_NO_REPLY",
        "USER_TRANSFER_MAIL_BODY_WITH_FILE_NO_REPLY",
        "USER_TRANSFER_MAIL_TITLE_NO_FILE_WITH_REPLY",
        "USER_TRANSFER_MAIL_BODY_NO_FILE_WITH_REPLY",
        "FILE_SHARE_DOWNLOAD_DUNNING_MAIL_FROM",
        "FILE_SHARE_DOWNLOAD_DUNNING_MAIL_TITLE",
        "FILE_SHARE_DOWNLOAD_DUNNING_MAIL_BODY",
        //ADD - 2018/04/06 - Fujinet - SF6.7.0_SF13-15-01 - END
        //ADD - 2018/07/24 - Fujinet - SF6.7.1_SF13-15-01 - START
        "USER_TRANSFER_NO_CONVERSION_APPROVAL_MAIL_FROM",
        "USER_TRANSFER_NO_CONVERSION_APPROVAL_MAIL_TITLE",
        "USER_TRANSFER_NO_CONVERSION_APPROVAL_MAIL_BODY",
        "USER_TRANSFER_NO_CONVERSION_APPROVAL_COMPLETION_MAIL_FROM",
        "USER_TRANSFER_NO_CONVERSION_APPROVAL_COMPLETION_MAIL_TITLE",
        "USER_TRANSFER_NO_CONVERSION_APPROVAL_COMPLETION_MAIL_BODY",
        "USER_TRANSFER_NO_CONVERSION_REJECT_COMPLETION_MAIL_FROM",
        "USER_TRANSFER_NO_CONVERSION_REJECT_COMPLETION_MAIL_TITLE",
        "USER_TRANSFER_NO_CONVERSION_REJECT_COMPLETION_MAIL_BODY",
        //ADD - 2018/07/24 - Fujinet - SF6.7.1_SF13-15-01 - END
        //ADD - 2020/10/26 - Fujinet - SF6.17.0_SF13-15-01 - START
        "FILE_SHARE_SUMIZUMI-KUN_QUARANTINE_ERROR_MAIL_FROM",
        "FILE_SHARE_SUMIZUMI-KUN_QUARANTINE_ERROR_MAIL_TITLE",
        "FILE_SHARE_SUMIZUMI-KUN_QUARANTINE_ERROR_MAIL_BODY"
        //ADD - 2020/10/26 - Fujinet - SF6.17.0_SF13-15-01 - END
        // ADD - 2021/03/04 - Fujinet - SF6.18.0_SF13-15-01 - START
        , "SUBSCRIPTION_LICENCE_NOTIFICATION_MAIL_FROM",
        "SUBSCRIPTION_LICENCE_NOTIFICATION_MAIL_TITLE",
        "SUBSCRIPTION_LICENCE_NOTIFICATION_MAIL_BODY"
        // ADD - 2021/03/04 - Fujinet - SF6.18.0_SF13-15-01 - END
        // ADD - 2021/05/18 - Fujinet - SF6.19.0_SF13-15-01_Issue #21 - START
        , "FILE_TRANSFER_PASSWORD_ALERT_MAIL_FROM",
        "FILE_TRANSFER_PASSWORD_ALERT_MAIL_TITLE",
        "FILE_TRANSFER_PASSWORD_ALERT_MAIL_BODY"
        // ADD - 2021/05/18 - Fujinet - SF6.19.0_SF13-15-01_Issue #21 - END
    ];

    public function __construct(EditableWord $editword, Request $request)
    {
        $this->model = $editword;
        $this->language_id = $request->language_id;
    }

    public function updateWord(Request $request)
    {
        $param = $request->only($this->word_id_array);
        if (empty($param) || empty($this->language_id))
            self::$error_flg = true;
        DB::connection('pgsql')->beginTransaction();
        try {
            foreach ($param as $key => $value) {
                $q = $this->model->where("editable_word_id", $key)->where('language_id', $this->language_id);
                if (empty($q->first())) {
                    throw new \Exception('no result for query');
                } else
                    $this->model->where("editable_word_id", $key)->where('language_id', $this->language_id)
                        ->update(['editable_word' => $value]);
            }
        } catch (\Exception $e) {
            DB::rollBack();
            return response()->json(['fail' => $e->getMessage()], 400);
        }


        if ($this->isError()) {
            DB::rollBack();
            return response()->json('fail', 400);

        } else {
            DB::connection('pgsql')->commit();
            return response()->json('success', 200);
        }


    }

    public function isError()
    {
        return self::$error_flg;

    }
}
